# action.yml
name: 'Send Email'
description: 'Sends email'
inputs:
  secret_pass:
    description: "..."
    required: true
  secret_mail:
    description: "..."
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SECRET_PASS: ${{ inputs.secret_pass }}
    SECRET_MAIL: ${{ inputs.secret_mail }}
  args:
    - ${{ envs.SECRET_PASS }} ${{ env.SECRET_MAIL }}